/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TieredSalesOwnableInterface extends ethers.utils.Interface {
  functions: {
    "configureTiering(uint256,(uint256,uint256,address,uint256,uint256,bytes32,uint256,uint256))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "configureTiering",
    values: [
      BigNumberish,
      {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "configureTiering",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class TieredSalesOwnable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TieredSalesOwnableInterface;

  functions: {
    "configureTiering(uint256,(uint256,uint256,address,uint256,uint256,bytes32,uint256,uint256))"(
      tierId: BigNumberish,
      tier: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "configureTiering(uint256[],tuple[])"(
      tierIds: BigNumberish[],
      tiers: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "configureTiering(uint256,(uint256,uint256,address,uint256,uint256,bytes32,uint256,uint256))"(
    tierId: BigNumberish,
    tier: {
      start: BigNumberish;
      end: BigNumberish;
      currency: string;
      price: BigNumberish;
      maxPerWallet: BigNumberish;
      merkleRoot: BytesLike;
      reserved: BigNumberish;
      maxAllocation: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "configureTiering(uint256[],tuple[])"(
    tierIds: BigNumberish[],
    tiers: {
      start: BigNumberish;
      end: BigNumberish;
      currency: string;
      price: BigNumberish;
      maxPerWallet: BigNumberish;
      merkleRoot: BytesLike;
      reserved: BigNumberish;
      maxAllocation: BigNumberish;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "configureTiering(uint256,(uint256,uint256,address,uint256,uint256,bytes32,uint256,uint256))"(
      tierId: BigNumberish,
      tier: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "configureTiering(uint256[],tuple[])"(
      tierIds: BigNumberish[],
      tiers: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    "configureTiering(uint256,(uint256,uint256,address,uint256,uint256,bytes32,uint256,uint256))"(
      tierId: BigNumberish,
      tier: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "configureTiering(uint256[],tuple[])"(
      tierIds: BigNumberish[],
      tiers: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "configureTiering(uint256,(uint256,uint256,address,uint256,uint256,bytes32,uint256,uint256))"(
      tierId: BigNumberish,
      tier: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "configureTiering(uint256[],tuple[])"(
      tierIds: BigNumberish[],
      tiers: {
        start: BigNumberish;
        end: BigNumberish;
        currency: string;
        price: BigNumberish;
        maxPerWallet: BigNumberish;
        merkleRoot: BytesLike;
        reserved: BigNumberish;
        maxAllocation: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
