/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ERC1155MintByOwnerERC2771,
  ERC1155MintByOwnerERC2771Interface,
} from "../ERC1155MintByOwnerERC2771";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintByOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103b8806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80635135bec114610030575b600080fd5b61004361003e366004610211565b610045565b005b7fc0ea367cb0174dd5521cd2372c76f8c13e6c1f832c71f1d6e0cbc185c9cc8ed45473ffffffffffffffffffffffffffffffffffffffff16610085610180565b73ffffffffffffffffffffffffffffffffffffffff1614610106576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601d60248201527f4f776e61626c653a2073656e646572206d757374206265206f776e6572000000604482015260640160405180910390fd5b6040517fb164884b000000000000000000000000000000000000000000000000000000008152309063b164884b90610148908790879087908790600401610301565b600060405180830381600087803b15801561016257600080fd5b505af1158015610176573d6000803e3d6000fd5b5050505050505050565b600061018a61018f565b905090565b7fdb1d5e345c4903e9a32b6674ecc8b1deaddbbb2551474fb34c9d34becbe7f4205460009073ffffffffffffffffffffffffffffffffffffffff1633036101dd575060131936013560601c90565b503390565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b6000806000806080858703121561022757600080fd5b843573ffffffffffffffffffffffffffffffffffffffff8116811461024b57600080fd5b93506020850135925060408501359150606085013567ffffffffffffffff8082111561027657600080fd5b818701915087601f83011261028a57600080fd5b81358181111561029c5761029c6101e2565b604051601f8201601f19908116603f011681019083821181831017156102c4576102c46101e2565b816040528281528a60208487010111156102dd57600080fd5b82602086016020830137600060208483010152809550505050505092959194509250565b73ffffffffffffffffffffffffffffffffffffffff8516815260006020858184015284604084015260806060840152835180608085015260005b818110156103575785810183015185820160a00152820161033b565b8181111561036957600060a083870101525b50601f01601f19169290920160a001969550505050505056fea2646970667358221220288de6284c77471571e78fe55ff1f1a66b873d4bb249ae5a897a3a30037eeb0064736f6c634300080f0033";

export class ERC1155MintByOwnerERC2771__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC1155MintByOwnerERC2771> {
    return super.deploy(overrides || {}) as Promise<ERC1155MintByOwnerERC2771>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC1155MintByOwnerERC2771 {
    return super.attach(address) as ERC1155MintByOwnerERC2771;
  }
  connect(signer: Signer): ERC1155MintByOwnerERC2771__factory {
    return super.connect(signer) as ERC1155MintByOwnerERC2771__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC1155MintByOwnerERC2771Interface {
    return new utils.Interface(_abi) as ERC1155MintByOwnerERC2771Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1155MintByOwnerERC2771 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC1155MintByOwnerERC2771;
  }
}
