/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC165Admin, IERC165AdminInterface } from "../IERC165Admin";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4[]",
        name: "interfaceIds",
        type: "bytes4[]",
      },
      {
        internalType: "bytes4[]",
        name: "interfaceIdsToRemove",
        type: "bytes4[]",
      },
    ],
    name: "setERC165",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC165Admin__factory {
  static readonly abi = _abi;
  static createInterface(): IERC165AdminInterface {
    return new utils.Interface(_abi) as IERC165AdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC165Admin {
    return new Contract(address, _abi, signerOrProvider) as IERC165Admin;
  }
}
