/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155MintByRole,
  IERC1155MintByRoleInterface,
} from "../IERC1155MintByRole";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "tos",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "mintByRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintByRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1155MintByRole__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155MintByRoleInterface {
    return new utils.Interface(_abi) as IERC1155MintByRoleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155MintByRole {
    return new Contract(address, _abi, signerOrProvider) as IERC1155MintByRole;
  }
}
