/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155Mintable,
  IERC1155MintableInterface,
} from "../IERC1155Mintable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintByFacet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1155Mintable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155MintableInterface {
    return new utils.Interface(_abi) as IERC1155MintableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155Mintable {
    return new Contract(address, _abi, signerOrProvider) as IERC1155Mintable;
  }
}
