/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155MetadataEvents,
  IERC1155MetadataEventsInterface,
} from "../IERC1155MetadataEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "value",
        type: "string",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "URI",
    type: "event",
  },
];

export class IERC1155MetadataEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155MetadataEventsInterface {
    return new utils.Interface(_abi) as IERC1155MetadataEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155MetadataEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC1155MetadataEvents;
  }
}
