/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC173Events, IERC173EventsInterface } from "../IERC173Events";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
];

export class IERC173Events__factory {
  static readonly abi = _abi;
  static createInterface(): IERC173EventsInterface {
    return new utils.Interface(_abi) as IERC173EventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC173Events {
    return new Contract(address, _abi, signerOrProvider) as IERC173Events;
  }
}
