/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155TieredSales,
  IERC1155TieredSalesInterface,
} from "../IERC1155TieredSales";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tierId",
        type: "uint256",
      },
    ],
    name: "tierToTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tierIds",
        type: "uint256[]",
      },
    ],
    name: "tierToTokenId",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC1155TieredSales__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155TieredSalesInterface {
    return new utils.Interface(_abi) as IERC1155TieredSalesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155TieredSales {
    return new Contract(address, _abi, signerOrProvider) as IERC1155TieredSales;
  }
}
