/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155Lockable,
  IERC1155LockableInterface,
} from "../IERC1155Lockable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "lockByFacet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "unlockByFacet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1155Lockable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155LockableInterface {
    return new utils.Interface(_abi) as IERC1155LockableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155Lockable {
    return new Contract(address, _abi, signerOrProvider) as IERC1155Lockable;
  }
}
