/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155TieredSalesAdmin,
  IERC1155TieredSalesAdminInterface,
} from "../IERC1155TieredSalesAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tierId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "configureTierTokenId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tierIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
    ],
    name: "configureTierTokenId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1155TieredSalesAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155TieredSalesAdminInterface {
    return new utils.Interface(_abi) as IERC1155TieredSalesAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155TieredSalesAdmin {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC1155TieredSalesAdmin;
  }
}
