/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC2771ContextAdmin,
  IERC2771ContextAdminInterface,
} from "../IERC2771ContextAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedForwarder",
        type: "address",
      },
    ],
    name: "setTrustedForwarder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC2771ContextAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IERC2771ContextAdminInterface {
    return new utils.Interface(_abi) as IERC2771ContextAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC2771ContextAdmin {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC2771ContextAdmin;
  }
}
