/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC1155SupplyAdmin,
  IERC1155SupplyAdminInterface,
} from "../IERC1155SupplyAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "setMaxSupply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "newValues",
        type: "uint256[]",
      },
    ],
    name: "setMaxSupplyBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1155SupplyAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155SupplyAdminInterface {
    return new utils.Interface(_abi) as IERC1155SupplyAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155SupplyAdmin {
    return new Contract(address, _abi, signerOrProvider) as IERC1155SupplyAdmin;
  }
}
