/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OwnableInternal,
  OwnableInternalInterface,
} from "../OwnableInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
];

export class OwnableInternal__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableInternalInterface {
    return new utils.Interface(_abi) as OwnableInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnableInternal {
    return new Contract(address, _abi, signerOrProvider) as OwnableInternal;
  }
}
